stages:
  - compile
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

before_script:
  - 'chmod +x mvnw'

compile:
  stage: compile
  script:
    - 'echo $JAVA_HOME'
    - './mvnw compile'

test:
  stage: test
  script:
    - './mvnw test'
    - "cat target/site/jacoco/index.html | grep -o '.*'"
    - './mvnw sonar:sonar -Dsonar.host.url=http://sonar.v99.nl -Dsonar.login=$SONAR_TOKEN'
  allow_failure: false
  coverage: "/Total.*?([0-9]{1,3})%/"
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

backend image:
  stage: build
  script:
    - 'docker build -t rachidd/gps-backend .'
  only:
    - master

frontend image:
  stage: build
  script:
    - 'cd frontend'
    - 'docker build -t rachidd/gps-frontend .'
  only:
    - master

cache:
  paths:
    - .m2/repository/
