image: docker:19.03.12

stages:
  - compile
  - test
  - build
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  FRONTEND_BUILD_ARGS: "--build-arg REACT_APP_AXIOS_BASE_URL=http://gradest-api.v99.nl/"

compile:
  image: adoptopenjdk/maven-openjdk11:latest
  stage: compile
  script:
    - 'mvn compile'

test:
  image: adoptopenjdk/maven-openjdk11:latest
  stage: test
  script:
    - 'mvn test'
    - "cat target/site/jacoco/index.html | grep -o '.*'"
    - 'mvn sonar:sonar -Dsonar.host.url=http://sonar.v99.nl -Dsonar.login=$SONAR_TOKEN'
  allow_failure: false
  coverage: "/Total.*?([0-9]{1,3})%/"
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

backend image:
  stage: build
  script:
    - 'docker build -t rachidd/gps-backend .'
  only:
    - master

frontend image:
  stage: build
  script:
    - 'cd frontend'
    - 'docker build $FRONTEND_BUILD_ARGS -t rachidd/gps-frontend .'
  only:
    - master

dockerhub:
  before_script:
    - 'echo "$DOCKER_REGISTRY_PASS" | docker login --username $DOCKER_REGISTRY_USER --password-stdin'
  stage: deploy
  script:
    - 'docker push rachidd/gps-backend'
    - 'docker push rachidd/gps-frontend'
  only:
    - master

cache:
  paths:
    - .m2/repository/
