# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # App backend service
  gps-backend:
    image: rachidd/tdb-backend:latest
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gradest?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: 'gradmin'
      SPRING_DATASOURCE_PASSWORD: 'gradmin'
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Frontend Service
  gps-frontend:
    image: rachidd/gps-frontend:latest
    ports:
      - "3000:80" # Map the exposed port 80 on the container to port 9090 on the host machine
    restart: always
    depends_on:
      - gps-backend
    networks:
      - frontend

  # Database Service (Mysql)
  db:
    image: mariadb/server:10.5
    ports:
      - "3300:3306"
    restart: always
    environment:
      MYSQL_DATABASE: gradest
      MYSQL_USER: gradmin
      MYSQL_PASSWORD: gradmin
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - db-gradest-data:/var/lib/mysql
    networks:
      - backend

# Volumes
volumes:
  db-gradest-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:
